### ISSUE TITLE
lua-resty-sniproxy use IPv6 only

### ISSUE THREAD

**Issue by wzk** [fffonion/lua-resty-sniproxy#4]
Hello,

      Thank you for your project of lua-resty-sniproxy, how can I setup sniproxy connect to upstream server only by IPv6? 

    Thanks a lot.

**Comment by fffonion** [comment]
You should use IPv6 addresses in square brackets notation, ie.:
```
sni_rules = {
     ["www.google.com"] = {"[2607:f8b0:4009:801::2004]", 443},
}
```

**Comment by wzk** [comment]
Thank you for you reply, because some domain has a lot of sub-domain, and each one has different IPv6 address, ie: *.googlevideo.com, so, is there an option let lua-resty-sniproxy use AAAA record first?

I also do some test on those situation, but the result is not what I want.

1. let lua-resty-sniproxy run on a ipv6 only host, nginx only listen on [::]443 port.
2. Use ip[6]tables to filter A record for dns reply packet.

**Comment by fffonion** [comment]
First you will need a dns server that returns AAAA records (like 8.8.8.8)
Then add `ipv6=on` to your configuration:
```
lua_resolver 8.8.8.8 ipv6=on;
```

**Comment by wzk** [comment]
I got it, thank you so much!
